name: 4CAC
description: 4 class classification of contigs.
keywords:
  - metagenome
  - classification
tools:
  - 4cac:
      description: 4CAC is a four-class classifier designed to classify contigs in mixed metagenome
          assemblies as phages, plasmids, prokaryotes (bacteria and archaea), microeukaryote
          (fungi and protozoa) or uncertain.
      homepage: https://github.com/Shamir-Lab/4CAC
      documentation: https://github.com/Shamir-Lab/4CAC
      licence: ["MIT License"]
      identifier: 4cac
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - contigs:
        type: path
        description: |
          List of input FastQ files of size 1 for single-end data and 4
          (unmerged_1, unmerged_2, merged, singletons) for paired-end data.
    - graph:
        type: path
        description: Assembly graph
    - paths:
        type: path
        description: Assembly paths
output:
  - classification:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - contig_classification:
          type: file
          description: Contig classification
          pattern: "4CAC_classification.fasta"
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.log":
          type: file
          description: 4cac log file
          pattern: "*.4cac.log"
authors:
  - "Niklaus Johner (niklaus.johner@chuv.ch)"
maintainers:
  - "Niklaus Johner (niklaus.johner@chuv.ch)"
