name: motus_profile
description: Taxonomic profiling using mOTUs
keywords:
  - metagenome
  - taxonomic
  - profiling
  - abundance
tools:
  - bbmap:
      description: mOTUs is a single copy marker gene based approach for taxonomic profiling of metagenomic data.
      homepage: https://github.com/motu-tool/mOTUs
      documentation: https://github.com/motu-tool/mOTUs/wiki
      licence: ["GNU General Public License v3.0"]
      identifier: motus
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: path
        description: |
          List of input FastQ files of size 1 for single-end data and 4
          (unmerged_1, unmerged_2, merged, singletons) for paired-end data.
output:
  - motus:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.motus":
          type: file
          description: motus profile file
          pattern: "*.motus"
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.log":
          type: file
          description: motus log file
          pattern: "*.motus.log"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "Niklaus Johner (niklaus.johner@chuv.ch)"
maintainers:
  - "Niklaus Johner (niklaus.johner@chuv.ch)"
