"""
This script will remove the files generated by assembly in
nextflow's work directory, provided that we do not need them anymore
(i.e. we have the files in the output directory).
"""

import argparse
import logging
import re
from collections import defaultdict
from pathlib import Path
from pprint import pprint as pp

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("clean-up")


preprocessing_files = [
    "{}_host_filtered_1.fastq.gz",
    "{}_merged.fastq.gz",
    "{}_host_filtered_2.fastq.gz",
    "{}_unmerged_1.fastq.gz",
    "{}_host_filtered_singletons.fastq.gz",
    "{}_unmerged_2.fastq.gz",
]

process_info = {
    "assembly": {
        "log": ".spades.log",
        "work_subdir": "assembly",
        "work_files": [
            "{}.assembly.gfa.gz",
            "{}.scaffolds.fa.gz",
            "{}.scaffolds.paths.gz",
            "{}.stats",
        ],
    },
    "trim": {
        "log": "_trimmed.bbduk.log",
        "work_subdir": "preprocessed_reads",
        "work_files": preprocessing_files,
    },
    "phix": {
        "log": "_phix_filtered.bbduk.log",
        "work_subdir": "preprocessed_reads",
        "work_files": preprocessing_files,
    },
    "quality_filter": {
        "log": "_quality_filtered.bbduk.log",
        "work_subdir": "preprocessed_reads",
        "work_files": preprocessing_files,
    },
    "filter_host": {
        "log": "_host_filtered.bbmap.log",
        "work_subdir": "preprocessed_reads",
        "work_files": preprocessing_files,
    },
    "filter_host_singletons": {
        "log": "_host_filtered_singletons.bbmap.log",
        "work_subdir": "preprocessed_reads",
        "work_files": preprocessing_files,
    },
    "filtersam": {
        "log": "_filtered.sam",
        "work_subdir": "gene_counts_gc",
        "work_files": ["{}_genes_per_cell.csv"],
    },
    "bwa_mem": {
        "search_expr": "bwa",
        "log": ".bam",
        "work_subdir": "gene_counts_gc",
        "work_files": ["{}_genes_per_cell.csv"],
    },
}


to_delete_expr = re.compile(r".*\.gz|.*\.fast.*|.*\.bam|.*\.sam|.*\.gfa")


class WorkDirCleaner:
    def __init__(self, work_dir, output_dir, dry_run):
        self.work_dir = Path(work_dir)
        self.output_dir = Path(output_dir)
        self.dry_run = dry_run

    def log_to_sample(self, log_file, ending):
        filename = log_file.name
        return filename.rstrip(ending)

    def __call__(self):
        sample_process_dirs = {}
        to_delete = {}
        for process, info in process_info.items():
            logger.info(f"Searching for {process}")
            sample_process_dirs[process] = defaultdict(list)
            if "search_expr" in info:
                dirs = self.work_dir.glob(f"**/*{info['search_expr']}")
                dirs_and_files = [
                    (d.parent, next(d.parent.glob(f"*{info['log']}")))
                    for d in dirs
                    if list(d.parent.glob(f"*{info['log']}"))
                ]
            else:
                logs = self.work_dir.glob(f"**/*{info['log']}")
                dirs_and_files = [(el.parent, el) for el in logs]
            for dir, log_file in dirs_and_files:
                sample_process_dirs[process][
                    self.log_to_sample(log_file, info["log"])
                ].append(dir)
            to_handle = []
            for sample, process_dirs in sample_process_dirs[process].items():
                subdir = Path(self.output_dir, sample, info["work_subdir"])
                delete = subdir.exists()
                for file in info["work_files"]:
                    if not (subdir / file.format(sample)).exists():
                        delete = False
                        break
                if not delete:
                    logger.info(f"skipping {sample}")
                    continue

                to_handle.extend(process_dirs)
            to_delete[process] = []
            for process_dir in to_handle:
                for file in process_dir.iterdir():
                    if (not file.is_file()) or file.is_symlink():
                        continue
                    if to_delete_expr.match(file.name):
                        to_delete[process].append(file)

        for process, info in process_info.items():
            tot_size = sum([file.stat().st_size for file in to_delete[process]])
            n_files = len(to_delete[process])
            logger.info(f"{process}:")
            logger.info(f"Deleting {n_files} files from {len(to_handle)} directories.")
            logger.info(f"This will free up {int(tot_size / 10**9)}GB.")
            print_files = input("print 20 first files? [y]/n")
            if print_files == "y":
                pp(to_delete[process][:20])

        if self.dry_run:
            return

        input("ctl-c to cancel")
        for process, info in process_info.items():
            logger.info(f"Cleaning up {process}")
            n_files = len(to_delete[process])
            for i, file in enumerate(to_delete[process], 1):
                file.unlink()
                if i % 100 == 0:
                    logger.info(f"Done {i}/{n_files}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser("clean_up_preprocessing.py")

    parser.add_argument(
        "-o",
        "--pipeline_outdir",
        default="output",
        type=Path,
        help="path to the output directory of the pipeline",
    )

    parser.add_argument(
        "-w",
        "--pipeline_workdir",
        default="work",
        type=Path,
        help="path to the work directory of the pipeline",
    )

    parser.add_argument(
        "-n",
        "--dry_run",
        action="store_true",
        help="Only list files that would get deleted.",
    )

    args = parser.parse_args()
    WorkDirCleaner(args.pipeline_workdir, args.pipeline_outdir, args.dry_run)()
