name: assembly_stats
description: Get assembly statistics from assembly-stats
keywords:
  - metagenome
  - taxonomic
  - profiling
  - abundance
tools:
  - assembly-stats:
      description: Get assembly statistics from FASTA and FASTQ files.
      homepage: https://github.com/sanger-pathogens/assembly-stats
      documentation: https://github.com/sanger-pathogens/assembly-stats
      licence: ["GNU General Public License v3.0"]
      identifier: assembly-stats
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - scaffolds:
        type: path
        description: Scaffolds file.
output:
  - stats:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.stats":
          type: file
          description: assembly statistics
          pattern: "*.stats"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "Niklaus Johner (niklaus.johner@chuv.ch)"
maintainers:
  - "Niklaus Johner (niklaus.johner@chuv.ch)"
